import { readFileSync } from "node:fs";
import { strict as assert } from "node:assert";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const root = fileURLToPath(new URL("..", import.meta.url));
const api = readFileSync(join(root, "src", "api.ts"), "utf8");
const picker = api.match(/async function listCodexModelsForPicker\(\): Promise<ModelInfo\[]> \{[\s\S]*?\n\}\n\nexport interface CodexAccountResponse/)?.[0] ?? "";
const claudePicker = api.match(/async function listClaudeModelsForPicker\(\): Promise<ModelInfo\[]> \{[\s\S]*?\n\}\n\nexport async function getClaudeStatus/)?.[0] ?? "";
const codexRun = api.match(/export async function streamCodexRun\([\s\S]*?\n\): Promise<void> \{/)?.[0] ?? "";
const claudeRun = api.match(/export async function streamClaudeRun\([\s\S]*?\n\): Promise<void> \{/)?.[0] ?? "";

assert.match(api, /const CODEX_PICKER_TIMEOUT_MS = 1500;/);
assert.ok(picker, "Codex picker function should exist");
assert.match(picker, /const ctrl = new AbortController\(\);[\s\S]*setTimeout\(\(\) => ctrl\.abort\(\), CODEX_PICKER_TIMEOUT_MS\);/);
assert.match(picker, /getCodexAccount\(false, ctrl\.signal\)/);
assert.match(picker, /authFetch\(`\$\{BASE\}\/codex\/models`, \{ signal: ctrl\.signal \}\)/);
assert.match(api, /supportedReasoningEfforts/);
assert.match(picker, /inputModalities/);
assert.match(picker, /finally \{[\s\S]*clearTimeout\(timer\);[\s\S]*\}/);
assert.match(api, /export const CLAUDE_MODEL_PREFIX = "claude:";/);
assert.ok(claudePicker, "Claude picker function should exist");
assert.match(claudePicker, /getClaudeStatus\(ctrl\.signal\)/);
assert.match(claudePicker, /CLAUDE_MODEL_PREFIX/);
assert.match(claudePicker, /supported_efforts: \["low", "medium", "high", "xhigh", "max"\]/);
assert.match(claudePicker, /finally \{[\s\S]*clearTimeout\(timer\);[\s\S]*\}/);
assert.match(api, /export type ReasoningEffort = "auto" \| "none" \| "minimal" \| "low" \| "medium" \| "high" \| "xhigh" \| "max";/);
assert.match(api, /function reasoningEffortBody\(reasoningEffort\?: ReasoningEffort\): \{ reasoning_effort\?: ReasoningEffort \}/);
assert.match(api, /return reasoningEffort && reasoningEffort !== "auto" \? \{ reasoning_effort: reasoningEffort \} : \{\};/);
assert.equal((api.match(/reasoningEffortBody\(reasoningEffort\)/g) ?? []).length, 2);
assert.match(api, /type: "image"; id: string; status: string; url: string/);
assert.match(codexRun, /thread_id\?: string;/);
assert.match(codexRun, /persist_thread\?: boolean;/);
assert.match(codexRun, /tool_approval_policy\?: ToolApprovalMode;/);
assert.match(codexRun, /tool_approval_grant\?: boolean;/);
assert.match(codexRun, /plan_mode\?: boolean;/);
assert.match(claudeRun, /session_id\?: string;/);
assert.match(claudeRun, /tool_approval_policy\?: ToolApprovalMode;/);
assert.match(claudeRun, /tool_approval_grant\?: boolean;/);
assert.match(claudeRun, /plan_mode\?: boolean;/);
assert.match(api, /\/codex\/login\/chatgpt-device/);
assert.match(api, /\/codex\/login\/api-key/);
